CREATE TABLE "GITLAB_REPO" (
 "ID" TEXT,
 "PRODUCT_ID" TEXT,
 "NAME" TEXT NOT NULL UNIQUE,
 "URL" TEXT UNIQUE,
 "TYPE" TEXT NOT NULL,
 "STATUS" TEXT NOT NULL,
 "GIT_STANDARDIZATION" INTEGER,
 "DOES_DOC_REPO_EXIST" INTEGER,
 FOREIGN KEY("PRODUCT_ID") REFERENCES "PRODUCT"("ID"),
 PRIMARY KEY("ID")
);
