ALTER TABLE "EPIC" ADD COLUMN "PROJECT_ID" TEXT REFERENCES "PROJECT"("ID");
ALTER TABLE "EPIC" ADD COLUMN "NUMBER_PER_PROJECT" INTEGER;

ALTER TABLE "STORY" ADD COLUMN "PROJECT_ID" TEXT REFERENCES "PROJECT"("ID");
ALTER TABLE "STORY" ADD COLUMN "NUMBER_PER_PROJECT" INTEGER;

ALTER TABLE "DEV_TASK" ADD COLUMN "PROJECT_ID" TEXT REFERENCES "PROJECT"("ID");
ALTER TABLE "DEV_TASK" ADD COLUMN "NUMBER_PER_PROJECT" INTEGER;

ALTER TABLE "DEV_SUB_TASK" ADD COLUMN "PROJECT_ID" TEXT REFERENCES "PROJECT"("ID");
ALTER TABLE "DEV_SUB_TASK" ADD COLUMN "NUMBER_PER_PROJECT" INTEGER;

ALTER TABLE "BUG" ADD COLUMN "PROJECT_ID" TEXT REFERENCES "PROJECT"("ID");
ALTER TABLE "BUG" ADD COLUMN "NUMBER_PER_PROJECT" INTEGER;

ALTER TABLE "ENHANCEMENT" ADD COLUMN "PROJECT_ID" TEXT REFERENCES "PROJECT"("ID");
ALTER TABLE "ENHANCEMENT" ADD COLUMN "NUMBER_PER_PROJECT" INTEGER;

ALTER TABLE "INCIDENT" ADD COLUMN "PROJECT_ID" TEXT REFERENCES "PROJECT"("ID");
ALTER TABLE "INCIDENT" ADD COLUMN "NUMBER_PER_PROJECT" INTEGER;

ALTER TABLE "NEW_FEATURE" ADD COLUMN "PROJECT_ID" TEXT REFERENCES "PROJECT"("ID");
ALTER TABLE "NEW_FEATURE" ADD COLUMN "NUMBER_PER_PROJECT" INTEGER;

ALTER TABLE "PROBLEM" ADD COLUMN "PROJECT_ID" TEXT REFERENCES "PROJECT"("ID");
ALTER TABLE "PROBLEM" ADD COLUMN "NUMBER_PER_PROJECT" INTEGER;

ALTER TABLE "PROPOSAL" ADD COLUMN "PROJECT_ID" TEXT REFERENCES "PROJECT"("ID");
ALTER TABLE "PROPOSAL" ADD COLUMN "NUMBER_PER_PROJECT" INTEGER;

