CREATE TABLE "PRODUCT" (
 "ID" TEXT,
 "PRODUCT_NUMBER" TEXT NOT NULL UNIQUE,
 "APPLICATION_SYMBOLIC_IDENTIFIER" TEXT NOT NULL UNIQUE,
 "PRODUCT_CODE" TEXT NOT NULL UNIQUE,
 "NAME" TEXT NOT NULL UNIQUE,
 "PRODUCT_GROUP_ID" TEXT,
 "STATUS" TEXT,
 "RESOLUTION" TEXT,
 "SORTKEY" INTEGER,
 "DESCRIPTION" TEXT,
 "DEFAULT_MILESTONE_ID" TEXT,
 PRIMARY KEY("ID"),
 FOREIGN KEY("PRODUCT_GROUP_ID") REFERENCES "PRODUCT_GROUP"("ID")
);
