CREATE TABLE "PRODUCT_RELEASE" (
 "ID" TEXT,
 "PRODUCT_ID" TEXT NOT NULL,
 "PRODUCT_VERSION_ID" TEXT NOT NULL,
 "RELEASE_DATE" TEXT NOT NULL,
 "GIT_STANDARDIZATION" INTEGER NOT NULL,
 "SONAR_QUBE" INTEGER NOT NULL,
 "TEST_COVERAGE" INTEGER NOT NULL,
 "CHECK_STYLE" INTEGER NOT NULL,
 FOREIGN KEY("PRODUCT_ID") REFERENCES "PRODUCT"("ID"),
 PRIMARY KEY("ID"),
 FOREIGN KEY("PRODUCT_VERSION_ID") REFERENCES "PRODUCT_VERSION"("ID")
);
