CREATE TABLE "PROJECT" (
 "ID" TEXT,
 "NAME" TEXT NOT NULL UNIQUE,
 "PROJECT_GROUP_ID" TEXT,
 "STATUS" TEXT,
 "RESOLUTION" TEXT,
 "SORTKEY" INTEGER,
 "DESCRIPTION" TEXT,
 PRIMARY KEY("ID"),
 FOREIGN KEY("PROJECT_GROUP_ID") REFERENCES "PROJECT_GROUP"("ID")
);
