ALTER TABLE "EPIC" ADD COLUMN "ASSIGNEE" TEXT REFERENCES "USER"("ID");
ALTER TABLE "STORY" ADD COLUMN "ASSIGNEE" TEXT REFERENCES "USER"("ID");
ALTER TABLE "DEV_TASK" ADD COLUMN "ASSIGNEE" TEXT REFERENCES "USER"("ID");
ALTER TABLE "DEV_SUB_TASK" ADD COLUMN "ASSIGNEE" TEXT REFERENCES "USER"("ID");
ALTER TABLE "BUG" ADD COLUMN "ASSIGNEE" TEXT REFERENCES "USER"("ID");

ALTER TABLE "ENHANCEMENT" ADD COLUMN "ASSIGNEE" TEXT REFERENCES "USER"("ID");
ALTER TABLE "INCIDENT" ADD COLUMN "ASSIGNEE" TEXT REFERENCES "USER"("ID");
ALTER TABLE "NEW_FEATURE" ADD COLUMN "ASSIGNEE" TEXT REFERENCES "USER"("ID");
ALTER TABLE "PROBLEM" ADD COLUMN "ASSIGNEE" TEXT REFERENCES "USER"("ID");
ALTER TABLE "PROPOSAL" ADD COLUMN "ASSIGNEE" TEXT REFERENCES "USER"("ID");

ALTER TABLE "EPIC" ADD COLUMN "REPORTER" TEXT REFERENCES "USER"("ID");
ALTER TABLE "STORY" ADD COLUMN "REPORTER" TEXT REFERENCES "USER"("ID");
ALTER TABLE "DEV_TASK" ADD COLUMN "REPORTER" TEXT REFERENCES "USER"("ID");
ALTER TABLE "DEV_SUB_TASK" ADD COLUMN "REPORTER" TEXT REFERENCES "USER"("ID");
ALTER TABLE "BUG" ADD COLUMN "REPORTER" TEXT REFERENCES "USER"("ID");

ALTER TABLE "ENHANCEMENT" ADD COLUMN "REPORTER" TEXT REFERENCES "USER"("ID");
ALTER TABLE "INCIDENT" ADD COLUMN "REPORTER" TEXT REFERENCES "USER"("ID");
ALTER TABLE "NEW_FEATURE" ADD COLUMN "REPORTER" TEXT REFERENCES "USER"("ID");
ALTER TABLE "PROBLEM" ADD COLUMN "REPORTER" TEXT REFERENCES "USER"("ID");
ALTER TABLE "PROPOSAL" ADD COLUMN "REPORTER" TEXT REFERENCES "USER"("ID");
