CREATE TABLE "PRODUCT_VERSION" (
 "ID" TEXT,
 "PRODUCT_ID" TEXT NOT NULL,
 "NAME" TEXT NOT NULL,
 "DESCRIPTION" TEXT,
 "RETIRED" INTEGER,
 "CANCELLED" INTEGER,
 FOREIGN KEY("PRODUCT_ID") REFERENCES "PRODUCT"("ID"),
 PRIMARY KEY("ID")
);
